[tool.black]
line-length = 120
target-version = ['py311']
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
addopts = "-ra --cov=src --cov=tests --cov-report=term-missing"
testpaths = ["tests"]
